# Numpy - Numerical Python

In [8]:
import numpy

In [2]:
print(numpy.__version__)

1.18.5


# Creating an array

In [12]:
array = numpy.array([1,2,3,4,5])  #integer list
print(array)
print(type(array))
array.dtype     #prints the data type stored in an array

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int32')

In [11]:
array = numpy.array([1,2,3,4,5])
print(array)
print(numpy.sum(array))

[1 2 3 4 5]
15


In [10]:
array = numpy.array([1,2.0,3,4,5])  #float list
print(array)
print(type(array))
array.dtype

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


dtype('float64')

# Numpy Basic Functions

In [18]:
array = numpy.array([1,2,3,4,5])  #integer list
print(array)
print(type(array))
array.dtype 
print(numpy.sum(array))  #sum
print(numpy.diff(array)) #difference
print(numpy.prod(array)) #product

[1 2 3 4 5]
<class 'numpy.ndarray'>
15
[1 1 1 1]
120


# 2D Array

In [25]:
arr=numpy.array([[1,2,3],[4,5,6],[7,8,9]]) #3 rows & 3 colums.
print(arr)
print(arr.shape) #shape is an attribute and not a function.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


# Zeros Function

In [27]:
arr=numpy.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
arr=numpy.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Identity Function

In [38]:
numpy.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random Function

In [41]:
arr=numpy.random.randn(5,5)
print(arr)

[[-0.89961779 -1.10882869  0.41641743  0.55844592 -1.28413448]
 [-0.46906568  1.24063297 -1.27402539 -2.29902839 -1.58492897]
 [ 0.11789168 -0.38225704 -1.57878531 -0.10381653 -0.41349112]
 [-0.30205784  0.27430798 -2.34579727  0.01703352 -1.72527446]
 [ 1.20715963 -0.37918639  0.03963023  0.80919223  0.63005239]]


# Indexing

In [52]:
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a.shape)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
(3, 3)
<class 'numpy.ndarray'>


# Range Function

In [9]:
a=numpy.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


# Reshape Function

In [15]:
numpy.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
numpy.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
numpy.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
numpy.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
numpy.arange(12).reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [21]:
numpy.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

# Two array matrix using Reshape Function

In [37]:
n=numpy.arange(12).reshape(2,2,3)  #2 arrays, 2 rows , 2 columns.
print("This is the function declared")
print(n)
print("This is the Zeroth Array")
print(n[0])
print("This is the First Array")
print(n[1])
print("This is index of Zeroth Array")
print(n[0][0][0])  #first zero represents the array, second represents the row, third represents the index or column
print(n[1][0][0])
print(n[0][1][1])
print(n[1][1][2])

This is the function declared
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
This is the Zeroth Array
[[0 1 2]
 [3 4 5]]
This is the First Array
[[ 6  7  8]
 [ 9 10 11]]
This is index of Zeroth Array
0
6
4
11


# Array Functions

In [42]:
a=numpy.arange(12).reshape(3,4)  #Sum of Matrices.
b=numpy.arange(12).reshape(3,4)
print("This is A matrix: ")
print(a)
print("This is B matrix: ")
print(b)
print("This is the Sum of Matrices A & B")
print(a+b)

This is A matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
This is B matrix: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [49]:
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])  
b=numpy.array([[9,8,7],[6,5,4],[3,2,1]])
print(a.dot(b))   #Dot Product.

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [48]:
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("This is 'a' matrix")
print(a)
print("This is Tranpose of 'a' matrix")
print(a.T)

This is 'a' matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
This is Tranpose of 'a' matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Linear Algebra

In [52]:
#Let's solve three equations and find a,b,c.
# Equation 1:  a+b+c=6
# Equation 2:  2a-b-z=-3
# Equation 3:  3b-2z=0
a=numpy.array([[1,1,1],[2,-1,-1],[0,3,-2]])  #type LHS values.
b=numpy.array([6,-3,0])    #type RHS values.
answer=numpy.linalg.solve(a,b)   #(linalg)linear algebra
print(answer)

[1. 2. 3.]
